#!/bin/bash
APP=symmetrical-meme-agent
DEST_PATH=/usr/local/sbin/$APP

# Allow user to edit config file plus keep old one
#
if [ -f "$DEST_PATH/agent_config.py" ]
then
    echo "$DEST_PATH/agent_config.py already exists. Creating backup."
    cp $DEST_PATH/agent_config.py $DEST_PATH/agent_config.py.backup
fi
